import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Native shells generated by Capacitor / iOS / Android — never our code.
    "android/**",
    "ios/**",
    // Built APK output dir
    "dist-apk/**",
    // Source assets (not code)
    "assets/**",
    // The duplicate `learnitquick/` subfolder the user keeps untracked
    // for their own purposes — never scan it.
    "learnitquick/**",
  ]),
]);

export default eslintConfig;
